### ISSUE TITLE
bug: Patching the placement does not always result in a downsync

### ISSUE THREAD

**Issue by effi-ofer** [kubestellar/kubestellar#1711] opened 2024-02-05 12:35 UTC
### Describe the bug

Creating a placement and deployment on the WDS results in a downsync of the deployment to the WEC. If we then patch the placement so it does not match, and then patch back again so it matches again, we sometimes do and sometimes don't see the downsynced deployment on the WEC. 

### Steps To Reproduce

$ kubectl --context wds1 patch placement nginx-placement --type=merge -p '{"spec": {"downsync": [{"objectSelectors": [{"matchLabels": {"app.kubernetes.io/name": "blah"}}]}]}}'; kubectl --context cluster1 get deployments -n nginx; kubectl --context wds1 patch placement nginx-placement --type=merge -p '{"spec": {"downsync": [{"objectSelectors": [{"matchLabels": {"app.kubernetes.io/name": "nginx"}}]}]}}'; kubectl --context cluster1 get deployments -n nginx

### Expected Behavior

Deployment get downsynced to WEC.

**Comment by pdettori** [comment] 2024-02-05 15:19
It seems like a duplicate of https://github.com/kubestellar/kubestellar/issues/1694 ?

**Comment by effi-ofer** [comment] 2024-02-07 08:49
> It seems like a duplicate of #1694 ?

If my understanding of 1694 is correct, then it deals with the case where a controller is down.  This is not what happens here, so I don't think this is a duplicate.

**Comment by MikeSpreitzer** [comment] 2024-02-07 15:05
No, there is a difference. Item 1 in #1694 is about changing the workload object. This issue (#1711) is about changing the Placement (BindingPolicy).

**Comment by effi-ofer** [comment] 2024-02-22 10:57
I confirmed this scenario no longer reproduce when running with the PR https://github.com/kubestellar/kubestellar/pull/1780 code base. We should reconfirm and close this issue once the PR merges.

**Comment by nirrozenbaum** [comment] 2024-02-27 11:20
@effi-ofer @ezrasilvera is this bug fixed in main after merging pluggable transport?

**Closed** 2024-02-27 19:59 UTC
Labels: kind/bug, end-of-march, fixed - pending PR
