### ISSUE TITLE
bug: It takes several minutes to delete an object from the WEC

### ISSUE THREAD

**Issue by cwiklik** [kubestellar/kubestellar#2287] opened 2024-07-02 16:39 UTC
### Describe the bug

So first, my hosting cluster and a WEC are created with K3D and running on MAC. On the hosting cluster I create a job with a label matching binding policy of the WEC. The job gets pulled to the WEC where it runs to completion. The status is pushed up to the hosting cluster. The label matching the bindingpolicy is deleted. The job is not listed in the Bindings object, but it is listed in the manifestwork in its1. It takes several minutes before the object is eventually deleted from the WEC. Sometimes it can take ~20 minutes. I've checked the transport-controller and kubestellar-controller-manager logs for errors and did not see anything alarming.

Versions of things:

export KUBESTELLAR_VERSION=0.23.0
export OCM_STATUS_ADDON_VERSION=0.2.0-rc10
export OCM_TRANSPORT_PLUGIN=0.1.11

K8s:
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.8+k3s1

Snapshot of job's pods on the WEC:

```
NAME                     READY   STATUS      RESTARTS   AGE
sample-job-q6kmw-7jgq5   0/1     Completed   0          13m
sample-job-q6kmw-d7969   0/1     Completed   0          13m
sample-job-q6kmw-272k5   0/1     Completed   0          13m
```

The above job completed in about 80s from the start.

BindingPolicy:

```
  clusterSelectors:
  - matchLabels:
      location-group: edge
      name: cluster1
  downsync:
  - objectSelectors:
    - matchLabels:
        kubestellar.io/cluster: cluster1
  wantSingletonReportedState: true
```

The label that was removed after job completion was: kubestellar.io/cluster: cluster1

The Job:

```
apiVersion: batch/v1
kind: Job
metadata:
  generateName: sample-job-
  namespace: default
  labels:
    kubestellar.io/cluster: cluster1
spec:
  parallelism: 3
  completions: 3

  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:v0.1.0
        args: ["50s"]
        resources:
          requests:
            cpu: 1
            memory: "200Mi"
          limits:
            memory: "200Mi"
            cpu: 1
      restartPolicy: Never
```

### Steps To Reproduce

1. Setup Hosting cluster with wds of type host and a WEC.
2. Create bindingpolicy for the WEC using spec as above.
3. Use a job from above or add a label to a sample job that matches the BP
4. Create a job on the hosting cluster and allow it to finish on the WEC
5. Edit the job on the hosting cluster and remove the label added in step 3
6. Watch the job pods on the WEC ( in my case these linger for several minutes) 

### Expected Behavior

When a label is removed from a job, it should be removed from the WEC fairly quickly

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by MikeSpreitzer** [comment] 2024-07-02 17:31
Is `its1` of type host?

In the steps to reproduce, are steps 3 and 4 talking about the same Job?

**Comment by MikeSpreitzer** [comment] 2024-07-02 17:33
Can you please share the debug log from the transport controller, along with notes about when you took the cardinal steps outlined above?

**Comment by MikeSpreitzer** [comment] 2024-07-02 18:01
@cwiklik: you are using your hosting cluster to play the role of WDS, right?

**Comment by MikeSpreitzer** [comment] 2024-07-02 20:12
BTW, #2288 added a ginkgo test scenario that flaps the relevant label on a workspace object. At the moment, the E2E test matrix does not cover k3d infrastructure nor using the hosting cluster as WDS.

**Comment by cwiklik** [comment] 2024-07-03 14:53
I have rebooted my mac and reinstalled my software stack I use for testing and I don't see delete delays. Looks like this issue can be closed with no fix needed. Its probably related to K3D but I have nothing to back this up. Should I close this issue?

**Comment by MikeSpreitzer** [comment] 2024-07-03 16:59
Closing for now because unable to reproduce. Please re-open if the problem re-appears.

**Closed by MikeSpreitzer** 2024-07-03 16:59 UTC
Labels: kind/bug
