### ISSUE TITLE
Helm Repository 404 - page not found error

### ISSUE THREAD

**Issue by rchen-devv** [kubestellar/kubestellar#2212] opened 2024-06-18 16:57 UTC
### Describe the bug

When clicking the link "KubeStellar's Helm Chart" it sends me to a page that gives me a 404 page not found error 
<img width="1719" alt="Screenshot 2024-06-18 at 12 53 53 PM" src="https://github.com/kubestellar/kubestellar/assets/169481903/79685886-7e3e-4995-8171-eeda3d823010">

### Steps To Reproduce

Go to the [helm repository site](https://helm.kubestellar.io/) and scroll down to the bottom of the page and click on the hyperlink "KubeStellar's Helm Chart" and it will send you to a 404 - page not found site.

### Expected Behavior

The link should send me to a site that has a site that can give me more information on how to use "KubeStellar's Helm Chart"

**Comment by ezrasilvera** [comment] 2024-06-19 08:52
Should be fixed as part of the we redesign.

**Comment by MikeSpreitzer** [comment] 2024-06-19 21:03
The [helm repository site](https://helm.kubestellar.io/) is part of the legacy system that we do not support any more. What pointed you to that?

**Comment by clubanderson** [comment] 2024-06-19 21:23
We could easily support this. It is a common practice for some projects to have this.

**Comment by MikeSpreitzer** [comment] 2024-06-20 00:51
@clubanderson: we _do_ publish Helm charts in the current system. They are published through OCI repos rather than GitHub repos. https://github.com/kubestellar/kubestellar/pkgs/container/kubestellar%2Fcore-chart is one example.

Getting back to the subject of this Issue, I am trying to find the root cause. @rchen-devv should never have looked at the [helm repository site](https://helm.kubestellar.io/), and I think it would be helpful to understand what led there.

**Comment by rchen-devv** [comment] 2024-06-20 00:56
@MikeSpreitzer I searched up helm kubestellar and its one of the first links that popped up on my end. 

[https://github.com/kubestellar/helm](https://github.com/kubestellar/helm)

I thought this will help me understand how to use helm a little bit more to install kubestellar but I guess I am not supposed to have access to this or look into part of the repository.

**Comment by MikeSpreitzer** [comment] 2024-06-20 02:10
@rchen-devv: thanks. I think you said that you found that site by doing a web search.

It was published for the world to see. Nobody was intended to be excluded. The problem is just that it is outdated, it is now misleading junk.

**Comment by clubanderson** [comment] 2024-07-10 13:13
helm.kubestellar.io content was torn down and replaced with links to existing documentation site for kubestellar. @rchen-devv please confirm and close this issue if it is no longer a valid issue.

/assign @rchen-devv

**Closed** 2024-07-10 15:32 UTC
Labels: kind/bug, duplicate
