### ISSUE TITLE
feature: denaturing view

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#353] opened 2023-05-04 19:54 UTC
### Feature Description

The current PoC design calls for a "denaturing view".  I have started on implementing that, see https://github.com/MikeSpreitzer/kcp-dev-kcp/tree/add-denaturing-view/pkg/virtual/denature .  We need to finish it.

### Proposed Solution

The current denaturing view successfully proxies all requests (as far as I know), decoding and re-encoding the request body if there is one.  The next step is to decode and re-encode the response body, if there is one.  After that comes the interesting part, denaturing the requests and re-naturing the responses.

### Alternative Solutions

Continue to limp along without this functionality.

### Want to contribute?

- [ ] I would like to work on this issue.

**Comment by clubanderson** [comment] 2023-07-07 19:55
is this a dupe of the hierarchy issue?  Or should this be the hierarchy issue?

**Comment by clubanderson** [comment] 2023-07-24 20:02
@MikeSpreitzer is this a dupe of the hierarchy issue or should this be the actual hierarchy issue?

**Comment by clubanderson** [comment] 2023-07-27 14:47
@ezrasilvera can this be considered as part of decoupling or logical clusters?

**Comment by clubanderson** [comment] 2023-07-27 14:50
issue requires extended discussions to determine if and when this feature is included.

**Comment by ezrasilvera** [comment] 2023-08-28 15:21
@clubanderson This is should be part of the decoupling for resources that are natively denatured today by KCP (e.g., pods) . In the future we want to support denaturing of any resource so this should have been implemented regardless of KCP. 
This is not a blocker or required for providers that denature natively like KubeFlex.

**Closed** 2024-02-26 15:57 UTC
Labels: kind/feature, decoup-kcp, main-legacy, legacy-auto-close
