### ISSUE TITLE
feature: Use kube-bind for apiexport and api-bind

### ISSUE THREAD

**Issue by ezrasilvera** [kubestellar/kubestellar#525] opened 2023-06-01 10:22 UTC
Integrate kube-bind into KubeStellar as an optional (or replacement) for KCP's export/bind capabilities. This should be working on different logical cluster providers. 
The initial PoC will be using KIND clusters as the logical clusters.

**Comment by fileppb** [comment] 2023-06-06 20:29
My last run was on 6/2. I used a VirtualBox ubuntu VM, created 2 clusters using kind, one for a consumer and the other for a producer, and was able to run the mangodb example as seen in the following consumer extract:
Start a terminal session for the Kubebind Consumer

C:\Users\RobertFilepp\kube-bind>vagrant ssh

vagrant@vagrant:~$ kubectl config use-context kind-kubebind-
consumer
Switched to context "kind-kubebind-consumer".
vagrant@vagrant:~$ cd /vagrant/kube-bind/
vagrant@vagrant:/vagrant/kube-bind$ kubectl apply -f deploy/crd
customresourcedefinition.apiextensions.k8s.io/apiservicebindings.kube-bind.io created
customresourcedefinition.apiextensions.k8s.io/apiserviceexportrequests.kube-bind.io created
customresourcedefinition.apiextensions.k8s.io/apiserviceexports.kube-bind.io created
customresourcedefinition.apiextensions.k8s.io/apiservicenamespaces.kube-bind.io created
customresourcedefinition.apiextensions.k8s.io/apiservices.kube-bind.io created
customresourcedefinition.apiextensions.k8s.io/clusterbindings.kube-bind.io created
vagrant@vagrant:/vagrant/kube-bind$ kubectl apply -f deploy/examples/crd-mangodb.yaml
customresourcedefinition.apiextensions.k8s.io/mangodbs.mangodb.com created

vagrant@vagrant:/vagrant/kube-bind$ export PATH="${PATH}:${HOME}/.krew/bin"
vagrant@vagrant:/vagrant/kube-bind$ kubectl bind http://127.0.0.1:8081/export
DISCLAIMER: This is a prototype. It will change in incompatible ways at any time.


To authenticate, visit in your browser:

        http://127.0.0.1:8081/authorize?c=1GNKq9&p=39343&s=4cgpcyhttp://127.0.0.1:8081/authorize?c=1GNKq9&p=39343&s=4cgpcy

🔑 Successfully authenticated to http://127.0.0.1:8081/export
🔒 Created secret kube-bind/kubeconfig-gg4th for host https://127.0.0.1:34867, namespace kube-bind-wmkmj
🚀 Executing: kubectl bind apiservice --remote-kubeconfig-namespace kube-bind --remote-kubeconfig-name kubeconfig-gg4th -f -
✨ Use "-o yaml" and "--dry-run" to get the APIServiceExportRequest and pass it to "kubectl bind apiservice" directly. Great for automation.
🚀 Deploying konnector v0.3.0 to namespace kube-bind.
✅ Created APIServiceBinding mangodbs.mangodb.com

NAME                                                  PROVIDER   READY   MESSAGE   AGE
apiservicebinding.kube-bind.io/mangodbs.mangodb.com
     False   Pending   0s

vagrant@vagrant:/vagrant/kube-bind$ kubectl get namespaces
NAME                 STATUS   AGE
default              Active   8h
kube-bind            Active   2m50s
kube-node-lease      Active   8h
kube-public          Active   8h
kube-system          Active   8h
local-path-storage   Active   8h


vagrant@vagrant:/vagrant/kube-bind$ kubectl get APIServiceBi
ndings
NAME                   PROVIDER   READY   MESSAGE   AGE
mangodbs.mangodb.com              True              94s

vagrant@vagrant:/vagrant/kube-bind$ kubectl describe APIServ
iceBinding mangodbs.mangodb.com
Name:         mangodbs.mangodb.com
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  kube-bind.io/v1alpha1
Kind:         APIServiceBinding
Metadata:
  Creation Timestamp:  2023-05-31T17:53:37Z
  Generation:          1
  Managed Fields:
    API Version:  kube-bind.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:spec:
        .:
        f:kubeconfigSecretRef:
          .:
          f:key:
          f:name:
          f:namespace:
    Manager:      kubectl-bind
    Operation:    Update
    Time:         2023-05-31T17:53:37Z
    API Version:  kube-bind.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
    Manager:      kubectl-bind
    Operation:    Update
    Subresource:  status
    Time:         2023-05-31T17:53:37Z
    API Version:  kube-bind.io/v1alpha1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
    Manager:         konnector
    Operation:       Update
    Subresource:     status
    Time:            2023-05-31T17:53:55Z
  Resource Version:  37264
  UID:               933f140a-4958-46f3-b1ae-70d2e38cb9e6
Spec:
  Kubeconfig Secret Ref:
    Key:        kubeconfig
    Name:       kubeconfig-gg4th
    Namespace:  kube-bind
Status:
  Conditions:
    Last Transition Time:  2023-05-31T17:53:55Z
    Status:                True
    Type:                  Ready
    Last Transition Time:  2023-05-31T17:53:55Z
    Status:                True
    Type:                  SecretValid
Events:                    <none>
vagrant@vagrant:/vagrant/kube-bind$ kubectl config current-c
ontext
kind-kubebind-consumer

**Comment by waltforme** [comment] 2023-06-12 17:14
In these [documented experiments](https://docs.google.com/document/d/15xdJoY3OEAFY2zxSGmiDzJDlskIq5mphhFku5Ft8JW8/edit?usp=sharing), I have multiple kube-bind consumers being able to consume one exported API. That is, a user edits the specs within consumer clusters -> specs are synced from consumers to the provider -> the controller reads the synced specs, works on them, and writes statuses -> the statuses are synced back to each of the consumers to be visible to the user.

**Comment by clubanderson** [comment] 2023-06-15 14:43
please move document to kubestellar folder

**Comment by clubanderson** [comment] 2023-06-15 14:44
please open issue to track tasks for moving this functionality into kubestellar

**Comment by waltforme** [comment] 2023-06-15 15:51
> please move document to kubestellar folder

Sure, right here:
https://docs.google.com/document/d/1ujzrI-lt4nMaBGfTKGAT5qM25WFhVNPDOjfWJ7tMqV8/edit?usp=sharing

**Comment by waltforme** [comment] 2023-06-26 16:13
Looks like the syncer of kube-bind is not working correctly. Changes of objects doesn't trigger the reconciliation of the status controller (which is part of the syncer).

I was able to identify the root cause which are bugs in the status controller's enqueuing functions.

We need to fix the syncer before we adapt it into our use case for edgeplacements. So I submitted a PR to kube-bind:
https://github.com/kube-bind/kube-bind/pull/166

**Comment by clubanderson** [comment] 2023-07-18 16:07
@waltforme can you estimate when you will be able to meet with Stefan to discuss possibilities for upstreaming to cube-bind?

**Comment by waltforme** [comment] 2023-07-18 21:28
Supports to cluster-scoped APIs in kube-bind is expected to be done within this week. _Right after that_, let's show what we have implemented and discuss it with Stefan.

**Comment by waltforme** [comment] 2023-07-27 20:37
PR was out, and the CI fails on two tests, one is lint and the other is go-test-e2e. I just fixed the first one. Will delve into the second one. I suspect there should be some changes in the e2e test itself because now the konnector has different expected behavior than before.

**Comment by clubanderson** [comment] 2023-08-01 13:16
moving to sprint 3 to track

**Comment by waltforme** [comment] 2023-08-28 14:55
The PR got reviewed and there are improvements to be made. I am working on the improvements, including
- write e2e test for cluster-scoped APIs;
- use a better way to represent cluster namespace in each of the cluster-scoped API objects;
- other minor improvements.
I still aim to finish the improvements and then update the PR within sprint 3.

**Comment by clubanderson** [comment] 2023-10-30 13:58
is this issue complete?  last update was on aug 28th.

**Comment by clubanderson** [comment] 2023-10-30 14:03
closing per @waltforme

**Closed by clubanderson** 2023-10-30 14:03 UTC
Labels: backend, decoup-kcp, kube-bind
