### ISSUE TITLE
bug: `-p ocm` failed

### ISSUE THREAD

**Issue by MikeSpreitzer** [kubestellar/kubestellar#1554] opened 2024-01-15 03:53 UTC
### Describe the bug

I tried the Setup in https://github.com/kubestellar/kubestellar/tree/ks-0.20/docs/content/v0.20#setup on my Apple Silicon MacOS 14.2.1 MacBook. It succeeded in earlier trials, but not this time. The following typescript starts with a demonstration of a blank state, then shows the trials, and finishes with some investigation.

```
mspreitz@mjs13 kubestellar % git status
On branch ks-0.20
Your branch is up to date with 'upstream/ks-0.20'.

nothing to commit, working tree clean

mspreitz@mjs13 kubestellar % kind get clusters
enabling experimental podman provider
No kind clusters found.

mspreitz@mjs13 kubestellar % git status
On branch ks-0.20
Your branch is up to date with 'upstream/ks-0.20'.

nothing to commit, working tree clean

mspreitz@mjs13 kubestellar % ps axlww | egrep -w 'kcp|mailbox|where-resolver|placement|dex|backend|konnector|space'            
  501 38082  3077   0  31  0 408626944   1392 -      S+   s000    0:00.00 egrep -w kcp|mailbox|where-resolver|placement|dex|backend|konnector|space

mspreitz@mjs13 kubestellar % kubectl config delete-context sm-mgt
error: cannot delete context sm-mgt, not in /Users/mspreitz/.kube/config

mspreitz@mjs13 kubestellar % docker ps -a
CONTAINER ID  IMAGE       COMMAND     CREATED     STATUS      PORTS       NAMES

mspreitz@mjs13 kubestellar % kflex init --create-kind
✔ Checking if kind is installed...
✔ Checking if a kubeflex kind instance already exists...
✔ Creating kind cluster...
enabling experimental podman provider
Creating cluster "kubeflex" ...
 ✓ Ensuring node image (kindest/node:v1.27.3) 🖼 
 ✓ Preparing nodes 📦  
 ✓ Writing configuration 📜 
 ✓ Starting control-plane 🕹️ 
 ✓ Installing CNI 🔌 
 ✓ Installing StorageClass 💾 
Set kubectl context to "kind-kubeflex"
You can now use your cluster with:

kubectl cluster-info --context kind-kubeflex

Not sure what to do next? 😅  Check out https://kind.sigs.k8s.io/docs/user/quick-start/
◑ Installing and patching nginx ingress...namespace/ingress-nginx created
serviceaccount/ingress-nginx created
serviceaccount/ingress-nginx-admission created
role.rbac.authorization.k8s.io/ingress-nginx created
role.rbac.authorization.k8s.io/ingress-nginx-admission created
clusterrole.rbac.authorization.k8s.io/ingress-nginx created
◒ Installing and patching nginx ingress...clusterrole.rbac.authorization.k8s.io/ingress-nginx-admission created
rolebinding.rbac.authorization.k8s.io/ingress-nginx created
rolebinding.rbac.authorization.k8s.io/ingress-nginx-admission created
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx created
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx-admission created
configmap/ingress-nginx-controller created
service/ingress-nginx-controller created
service/ingress-nginx-controller-admission created
deployment.apps/ingress-nginx-controller created
job.batch/ingress-nginx-admission-create created
job.batch/ingress-nginx-admission-patch created
ingressclass.networking.k8s.io/nginx created
validatingwebhookconfiguration.admissionregistration.k8s.io/ingress-nginx-admission created
◐ Installing and patching nginx ingress...deployment.apps/ingress-nginx-controller patched
✔ Installing and patching nginx ingress...
✔ Kubeflex v0.3.3.3950897 2023-12-09T02:57:20Z
✔ Ensuring kubeflex-system namespace...
✔ Checking if OpenShift cluster...
✔ Installing shared backend DB...
✔ Waiting for shared backend DB to become ready...
✔ Installing kubeflex operator...
✔ Waiting for kubeflex operator to become ready...

mspreitz@mjs13 kubestellar % kflex create imbs1 --type vcluster -p ocm
✔ Checking for saved initial context...
✔ Switching to initial context...
✔ Creating new control plane imbs1 of type vcluster ...
✔ Waiting for API server to become ready...

mspreitz@mjs13 kubestellar % helm --kube-context imbs1 upgrade --install status-addon -n open-cluster-management oci://quay.io/pdettori/status-addon-chart --version 0.1.0
Release "status-addon" does not exist. Installing it now.
Pulled: quay.io/pdettori/status-addon-chart:0.1.0
Digest: sha256:2a07508cea42b40f2167afe8b4c0e96dbd68162010d8b2c67322e266f004526b
Error: unable to build kubernetes objects from release manifest: resource mapping not found for name: "addon-status" namespace: "open-cluster-management" from "": no matches for kind "ClusterManagementAddOn" in version "addon.open-cluster-management.io/v1alpha1"
ensure CRDs are installed first

mspreitz@mjs13 kubestellar % kubectl api-resources
NAME                              SHORTNAMES   APIVERSION                             NAMESPACED   KIND
bindings                                       v1                                     true         Binding
componentstatuses                 cs           v1                                     false        ComponentStatus
configmaps                        cm           v1                                     true         ConfigMap
endpoints                         ep           v1                                     true         Endpoints
events                            ev           v1                                     true         Event
limitranges                       limits       v1                                     true         LimitRange
namespaces                        ns           v1                                     false        Namespace
nodes                             no           v1                                     false        Node
persistentvolumeclaims            pvc          v1                                     true         PersistentVolumeClaim
persistentvolumes                 pv           v1                                     false        PersistentVolume
pods                              po           v1                                     true         Pod
podtemplates                                   v1                                     true         PodTemplate
replicationcontrollers            rc           v1                                     true         ReplicationController
resourcequotas                    quota        v1                                     true         ResourceQuota
secrets                                        v1                                     true         Secret
serviceaccounts                   sa           v1                                     true         ServiceAccount
services                          svc          v1                                     true         Service
mutatingwebhookconfigurations                  admissionregistration.k8s.io/v1        false        MutatingWebhookConfiguration
validatingwebhookconfigurations                admissionregistration.k8s.io/v1        false        ValidatingWebhookConfiguration
customresourcedefinitions         crd,crds     apiextensions.k8s.io/v1                false        CustomResourceDefinition
apiservices                                    apiregistration.k8s.io/v1              false        APIService
controllerrevisions                            apps/v1                                true         ControllerRevision
daemonsets                        ds           apps/v1                                true         DaemonSet
deployments                       deploy       apps/v1                                true         Deployment
replicasets                       rs           apps/v1                                true         ReplicaSet
statefulsets                      sts          apps/v1                                true         StatefulSet
tokenreviews                                   authentication.k8s.io/v1               false        TokenReview
localsubjectaccessreviews                      authorization.k8s.io/v1                true         LocalSubjectAccessReview
selfsubjectaccessreviews                       authorization.k8s.io/v1                false        SelfSubjectAccessReview
selfsubjectrulesreviews                        authorization.k8s.io/v1                false        SelfSubjectRulesReview
subjectaccessreviews                           authorization.k8s.io/v1                false        SubjectAccessReview
horizontalpodautoscalers          hpa          autoscaling/v2                         true         HorizontalPodAutoscaler
cronjobs                          cj           batch/v1                               true         CronJob
jobs                                           batch/v1                               true         Job
certificatesigningrequests        csr          certificates.k8s.io/v1                 false        CertificateSigningRequest
leases                                         coordination.k8s.io/v1                 true         Lease
endpointslices                                 discovery.k8s.io/v1                    true         EndpointSlice
events                            ev           events.k8s.io/v1                       true         Event
flowschemas                                    flowcontrol.apiserver.k8s.io/v1beta3   false        FlowSchema
prioritylevelconfigurations                    flowcontrol.apiserver.k8s.io/v1beta3   false        PriorityLevelConfiguration
helmchartconfigs                               helm.cattle.io/v1                      true         HelmChartConfig
helmcharts                                     helm.cattle.io/v1                      true         HelmChart
addons                                         k3s.cattle.io/v1                       true         Addon
ingressclasses                                 networking.k8s.io/v1                   false        IngressClass
ingresses                         ing          networking.k8s.io/v1                   true         Ingress
networkpolicies                   netpol       networking.k8s.io/v1                   true         NetworkPolicy
runtimeclasses                                 node.k8s.io/v1                         false        RuntimeClass
poddisruptionbudgets              pdb          policy/v1                              true         PodDisruptionBudget
clusterrolebindings                            rbac.authorization.k8s.io/v1           false        ClusterRoleBinding
clusterroles                                   rbac.authorization.k8s.io/v1           false        ClusterRole
rolebindings                                   rbac.authorization.k8s.io/v1           true         RoleBinding
roles                                          rbac.authorization.k8s.io/v1           true         Role
priorityclasses                   pc           scheduling.k8s.io/v1                   false        PriorityClass
csidrivers                                     storage.k8s.io/v1                      false        CSIDriver
csinodes                                       storage.k8s.io/v1                      false        CSINode
csistoragecapacities                           storage.k8s.io/v1                      true         CSIStorageCapacity
storageclasses                    sc           storage.k8s.io/v1                      false        StorageClass
volumeattachments                              storage.k8s.io/v1                      false        VolumeAttachment

mspreitz@mjs13 kubestellar % kubectl get pods -A
NAMESPACE     NAME                       READY   STATUS    RESTARTS   AGE
kube-system   coredns-68559449b6-g7w7s   1/1     Running   0          3m20s

mspreitz@mjs13 kubestellar % kubectl get ns
NAME                          STATUS   AGE
default                       Active   4m29s
kube-system                   Active   4m29s
kube-public                   Active   4m29s
kube-node-lease               Active   4m29s
open-cluster-management       Active   19s
open-cluster-management-hub   Active   5s

mspreitz@mjs13 kubestellar % kflex ctx
✔ Checking for saved initial context...
✔ Switching to initial context...

mspreitz@mjs13 kubestellar % kubectl get PostCreateHook
NAME             SYNCED   READY   TYPE   AGE
kslight                                  9m51s
ocm                                      9m51s
openshift-crds                           9m51s

mspreitz@mjs13 kubestellar % kubectl get PostCreateHook ocm -o yaml
apiVersion: tenancy.kflex.kubestellar.org/v1alpha1
kind: PostCreateHook
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"tenancy.kflex.kubestellar.org/v1alpha1","kind":"PostCreateHook","metadata":{"annotations":{},"labels":{"kflex.kubestellar.io/cptype":"imbs"},"name":"ocm"},"spec":{"templates":[{"apiVersion":"batch/v1","kind":"Job","metadata":{"name":"{{.HookName}}"},"spec":{"backoffLimit":1,"template":{"spec":{"containers":[{"args":["init"],"env":[{"name":"KUBECONFIG","value":"/etc/kube/config-incluster"}],"image":"quay.io/pdettori/clusteradm:0.7.1","name":"{{.HookName}}","volumeMounts":[{"mountPath":"/etc/kube","name":"kubeconfig","readOnly":true}]}],"restartPolicy":"Never","volumes":[{"name":"kubeconfig","secret":{"secretName":"vc-vcluster"}}]}}}}]}}
  creationTimestamp: "2024-01-15T03:32:37Z"
  generation: 1
  labels:
    kflex.kubestellar.io/cptype: imbs
  name: ocm
  resourceVersion: "743"
  uid: c72821ba-8f6d-4da8-b7c3-83ddf81265f5
spec:
  templates:
  - apiVersion: batch/v1
    kind: Job
    metadata:
      name: '{{.HookName}}'
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - args:
            - init
            env:
            - name: KUBECONFIG
              value: /etc/kube/config-incluster
            image: quay.io/pdettori/clusteradm:0.7.1
            name: '{{.HookName}}'
            volumeMounts:
            - mountPath: /etc/kube
              name: kubeconfig
              readOnly: true
          restartPolicy: Never
          volumes:
          - name: kubeconfig
            secret:
              secretName: vc-vcluster

mspreitz@mjs13 kubestellar % kflex ctx imbs1
✔ Switching to context imbs1...

mspreitz@mjs13 kubestellar % kubectl get jobs -A
No resources found

mspreitz@mjs13 kubestellar % which kflex
/opt/homebrew/bin/kflex

mspreitz@mjs13 kubestellar % kflex version
Kubeflex version: v0.3.3.3950897 2023-12-09T02:57:20Z
Kubernetes version: v1.27.2+k3s1

mspreitz@mjs13 kubestellar % git rev-parse HEAD
904703e9b47cb9d168ff17cb0af52fd21e1209d8

mspreitz@mjs13 kubestellar % brew list | grep -i flex
kubeflex
```

### Steps To Reproduce

See above.

### Expected Behavior

It works.

**Comment by MikeSpreitzer** [comment] 2024-01-15 04:13
I rebooted and tried again. Now I get exactly one OCM resource defined in imbs1 but still no Job.

```
mspreitz@mjs13 kubestellar % kubectl api-resources
NAME                              SHORTNAMES   APIVERSION                               NAMESPACED   KIND
bindings                                       v1                                       true         Binding
componentstatuses                 cs           v1                                       false        ComponentStatus
configmaps                        cm           v1                                       true         ConfigMap
endpoints                         ep           v1                                       true         Endpoints
events                            ev           v1                                       true         Event
limitranges                       limits       v1                                       true         LimitRange
namespaces                        ns           v1                                       false        Namespace
nodes                             no           v1                                       false        Node
persistentvolumeclaims            pvc          v1                                       true         PersistentVolumeClaim
persistentvolumes                 pv           v1                                       false        PersistentVolume
pods                              po           v1                                       true         Pod
podtemplates                                   v1                                       true         PodTemplate
replicationcontrollers            rc           v1                                       true         ReplicationController
resourcequotas                    quota        v1                                       true         ResourceQuota
secrets                                        v1                                       true         Secret
serviceaccounts                   sa           v1                                       true         ServiceAccount
services                          svc          v1                                       true         Service
mutatingwebhookconfigurations                  admissionregistration.k8s.io/v1          false        MutatingWebhookConfiguration
validatingwebhookconfigurations                admissionregistration.k8s.io/v1          false        ValidatingWebhookConfiguration
customresourcedefinitions         crd,crds     apiextensions.k8s.io/v1                  false        CustomResourceDefinition
apiservices                                    apiregistration.k8s.io/v1                false        APIService
controllerrevisions                            apps/v1                                  true         ControllerRevision
daemonsets                        ds           apps/v1                                  true         DaemonSet
deployments                       deploy       apps/v1                                  true         Deployment
replicasets                       rs           apps/v1                                  true         ReplicaSet
statefulsets                      sts          apps/v1                                  true         StatefulSet
tokenreviews                                   authentication.k8s.io/v1                 false        TokenReview
localsubjectaccessreviews                      authorization.k8s.io/v1                  true         LocalSubjectAccessReview
selfsubjectaccessreviews                       authorization.k8s.io/v1                  false        SelfSubjectAccessReview
selfsubjectrulesreviews                        authorization.k8s.io/v1                  false        SelfSubjectRulesReview
subjectaccessreviews                           authorization.k8s.io/v1                  false        SubjectAccessReview
horizontalpodautoscalers          hpa          autoscaling/v2                           true         HorizontalPodAutoscaler
cronjobs                          cj           batch/v1                                 true         CronJob
jobs                                           batch/v1                                 true         Job
certificatesigningrequests        csr          certificates.k8s.io/v1                   false        CertificateSigningRequest
leases                                         coordination.k8s.io/v1                   true         Lease
endpointslices                                 discovery.k8s.io/v1                      true         EndpointSlice
events                            ev           events.k8s.io/v1                         true         Event
flowschemas                                    flowcontrol.apiserver.k8s.io/v1beta3     false        FlowSchema
prioritylevelconfigurations                    flowcontrol.apiserver.k8s.io/v1beta3     false        PriorityLevelConfiguration
helmchartconfigs                               helm.cattle.io/v1                        true         HelmChartConfig
helmcharts                                     helm.cattle.io/v1                        true         HelmChart
addons                                         k3s.cattle.io/v1                         true         Addon
ingressclasses                                 networking.k8s.io/v1                     false        IngressClass
ingresses                         ing          networking.k8s.io/v1                     true         Ingress
networkpolicies                   netpol       networking.k8s.io/v1                     true         NetworkPolicy
runtimeclasses                                 node.k8s.io/v1                           false        RuntimeClass
clustermanagers                                operator.open-cluster-management.io/v1   false        ClusterManager
poddisruptionbudgets              pdb          policy/v1                                true         PodDisruptionBudget
clusterrolebindings                            rbac.authorization.k8s.io/v1             false        ClusterRoleBinding
clusterroles                                   rbac.authorization.k8s.io/v1             false        ClusterRole
rolebindings                                   rbac.authorization.k8s.io/v1             true         RoleBinding
roles                                          rbac.authorization.k8s.io/v1             true         Role
priorityclasses                   pc           scheduling.k8s.io/v1                     false        PriorityClass
csidrivers                                     storage.k8s.io/v1                        false        CSIDriver
csinodes                                       storage.k8s.io/v1                        false        CSINode
csistoragecapacities                           storage.k8s.io/v1                        true         CSIStorageCapacity
storageclasses                    sc           storage.k8s.io/v1                        false        StorageClass
volumeattachments                              storage.k8s.io/v1                        false        VolumeAttachment

mspreitz@mjs13 kubestellar % kubectl get jobs -A
No resources found
```

**Comment by pdettori** [comment] 2024-01-15 04:53
The job defined in the post-create-hook runs in the hosting cluster. To see the job, you should do:

```
$ kubectl --context kind-kubeflex -n imbs1-system get jobs
NAME                  COMPLETIONS   DURATION   AGE
ocm                   1/1           28s        4d14h
update-cluster-info   1/1           63s        4d14h
```

The ocm job is the one you want to check. Note, the clusteradm installs a Klusterlet operator that then installs the Registration and Work controllers. Initally you'd see only one CRD, then once the Klusterlet operator starts, it installs all the other CRDs. Installing the add-on right after installing the Klusterlet operator may not work, some polling is required until the needed CRDs are present.

**Comment by pdettori** [comment] 2024-01-15 04:55
`clustermanagers                                operator.open-cluster-management.io/v1   false  ` is the API resource installed by clusteradm (as CRD) together with the Klusterlet operator.

**Comment by MikeSpreitzer** [comment] 2024-01-15 06:10
After turning my attention elsewhere for hours, I looked again, and found many more OCM resources had gotten defined.

```
mspreitz@mjs13 kubestellar % kubectl api-resources
NAME                              SHORTNAMES                     APIVERSION                                    NAMESPACED   KIND
bindings                                                         v1                                            true         Binding
componentstatuses                 cs                             v1                                            false        ComponentStatus
configmaps                        cm                             v1                                            true         ConfigMap
endpoints                         ep                             v1                                            true         Endpoints
events                            ev                             v1                                            true         Event
limitranges                       limits                         v1                                            true         LimitRange
namespaces                        ns                             v1                                            false        Namespace
nodes                             no                             v1                                            false        Node
persistentvolumeclaims            pvc                            v1                                            true         PersistentVolumeClaim
persistentvolumes                 pv                             v1                                            false        PersistentVolume
pods                              po                             v1                                            true         Pod
podtemplates                                                     v1                                            true         PodTemplate
replicationcontrollers            rc                             v1                                            true         ReplicationController
resourcequotas                    quota                          v1                                            true         ResourceQuota
secrets                                                          v1                                            true         Secret
serviceaccounts                   sa                             v1                                            true         ServiceAccount
services                          svc                            v1                                            true         Service
addondeploymentconfigs                                           addon.open-cluster-management.io/v1alpha1     true         AddOnDeploymentConfig
addontemplates                                                   addon.open-cluster-management.io/v1alpha1     false        AddOnTemplate
clustermanagementaddons           cma,cmas                       addon.open-cluster-management.io/v1alpha1     false        ClusterManagementAddOn
managedclusteraddons              mca,mcas                       addon.open-cluster-management.io/v1alpha1     true         ManagedClusterAddOn
mutatingwebhookconfigurations                                    admissionregistration.k8s.io/v1               false        MutatingWebhookConfiguration
validatingwebhookconfigurations                                  admissionregistration.k8s.io/v1               false        ValidatingWebhookConfiguration
customresourcedefinitions         crd,crds                       apiextensions.k8s.io/v1                       false        CustomResourceDefinition
apiservices                                                      apiregistration.k8s.io/v1                     false        APIService
controllerrevisions                                              apps/v1                                       true         ControllerRevision
daemonsets                        ds                             apps/v1                                       true         DaemonSet
deployments                       deploy                         apps/v1                                       true         Deployment
replicasets                       rs                             apps/v1                                       true         ReplicaSet
statefulsets                      sts                            apps/v1                                       true         StatefulSet
tokenreviews                                                     authentication.k8s.io/v1                      false        TokenReview
localsubjectaccessreviews                                        authorization.k8s.io/v1                       true         LocalSubjectAccessReview
selfsubjectaccessreviews                                         authorization.k8s.io/v1                       false        SelfSubjectAccessReview
selfsubjectrulesreviews                                          authorization.k8s.io/v1                       false        SelfSubjectRulesReview
subjectaccessreviews                                             authorization.k8s.io/v1                       false        SubjectAccessReview
horizontalpodautoscalers          hpa                            autoscaling/v2                                true         HorizontalPodAutoscaler
cronjobs                          cj                             batch/v1                                      true         CronJob
jobs                                                             batch/v1                                      true         Job
certificatesigningrequests        csr                            certificates.k8s.io/v1                        false        CertificateSigningRequest
addonplacementscores                                             cluster.open-cluster-management.io/v1alpha1   true         AddOnPlacementScore
managedclusters                   mcl,mcls                       cluster.open-cluster-management.io/v1         false        ManagedCluster
managedclustersetbindings         mclsetbinding,mclsetbindings   cluster.open-cluster-management.io/v1beta2    true         ManagedClusterSetBinding
managedclustersets                mclset,mclsets                 cluster.open-cluster-management.io/v1beta2    false        ManagedClusterSet
placementdecisions                                               cluster.open-cluster-management.io/v1beta1    true         PlacementDecision
placements                                                       cluster.open-cluster-management.io/v1beta1    true         Placement
leases                                                           coordination.k8s.io/v1                        true         Lease
endpointslices                                                   discovery.k8s.io/v1                           true         EndpointSlice
events                            ev                             events.k8s.io/v1                              true         Event
flowschemas                                                      flowcontrol.apiserver.k8s.io/v1beta3          false        FlowSchema
prioritylevelconfigurations                                      flowcontrol.apiserver.k8s.io/v1beta3          false        PriorityLevelConfiguration
helmchartconfigs                                                 helm.cattle.io/v1                             true         HelmChartConfig
helmcharts                                                       helm.cattle.io/v1                             true         HelmChart
addons                                                           k3s.cattle.io/v1                              true         Addon
ingressclasses                                                   networking.k8s.io/v1                          false        IngressClass
ingresses                         ing                            networking.k8s.io/v1                          true         Ingress
networkpolicies                   netpol                         networking.k8s.io/v1                          true         NetworkPolicy
runtimeclasses                                                   node.k8s.io/v1                                false        RuntimeClass
clustermanagers                                                  operator.open-cluster-management.io/v1        false        ClusterManager
poddisruptionbudgets              pdb                            policy/v1                                     true         PodDisruptionBudget
clusterrolebindings                                              rbac.authorization.k8s.io/v1                  false        ClusterRoleBinding
clusterroles                                                     rbac.authorization.k8s.io/v1                  false        ClusterRole
rolebindings                                                     rbac.authorization.k8s.io/v1                  true         RoleBinding
roles                                                            rbac.authorization.k8s.io/v1                  true         Role
priorityclasses                   pc                             scheduling.k8s.io/v1                          false        PriorityClass
csidrivers                                                       storage.k8s.io/v1                             false        CSIDriver
csinodes                                                         storage.k8s.io/v1                             false        CSINode
csistoragecapacities                                             storage.k8s.io/v1                             true         CSIStorageCapacity
storageclasses                    sc                             storage.k8s.io/v1                             false        StorageClass
volumeattachments                                                storage.k8s.io/v1                             false        VolumeAttachment
manifestworkreplicasets           mwrs                           work.open-cluster-management.io/v1alpha1      true         ManifestWorkReplicaSet
manifestworks                                                    work.open-cluster-management.io/v1            true         ManifestWork
```

**Comment by pdettori** [comment] 2024-01-15 15:09
@MikeSpreitzer what you showed in the last typescript seems to validate what I mentioned. After `clusteradm join` command is ran in by the PCH job, it takes some time for the OCM CRDs to show up, since clusteradm installs an operator and a single API resource (clustermanagers) and then it take some time for that operator to start and install all the other CRDs. This is why running `helm --kube-context imbs1 upgrade --install status-addon ...` right after `kflex create imbs1 --type vcluster -p ocm` fails. If we want to automate this flow, we should have a loop with poll and sleep until the required OCM resources (clustermanagementaddons) show up.  It would be useful also to keep track of how much time it usually takes for those resources to show up.

**Comment by MikeSpreitzer** [comment] 2024-01-16 14:45
Yes, the script should definitely have a wait. This is a comment about what users read as well as any other script that gets execute (@effi-ofer, please take note).

I am surprised that it now takes long enough to make me think it did not happen, but previously it was so quick that I did not have any trouble. I am going to look into that.

**Comment by MikeSpreitzer** [comment] 2024-01-16 15:10
I just tried it again, and the PCH finished quickly this time.

**Comment by pdettori** [comment] 2024-01-16 15:59
It would be useful if other users report their experience here, so we can get some rough stats on how common is this issue. If the issue is widespread and repeatable we should open the issue with the OCM project.

**Comment by effi-ofer** [comment] 2024-01-18 12:29
I noticed that occasionally I need to wait as well, but never more than two or three minutes.  It hasn't been painful enough for me to time it until now.  Would the ocm be the right thing to wait on?

**Comment by pdettori** [comment] 2024-01-18 13:37
I would wait for the presence of the API resource `clustermanagementaddons` as that is what the status-add on, which is installed next, requires.

**Comment by MikeSpreitzer** [comment] 2024-01-23 06:48
The e2e tests and the user instructions now say to wait for the the OCM setup to be done enough. Can we close this now?

**Comment by pdettori** [comment] 2024-01-23 12:59
Yes, let's close this

**Closed by pdettori** 2024-01-23 12:59 UTC
Labels: kind/bug
