### ISSUE TITLE
bug:  `kflex create imbs1 --type vcluster -p ocm` not working

### ISSUE THREAD

**Issue by francostellari** [kubestellar/kubestellar#1584] opened 2024-01-18 18:13 UTC
### Describe the bug

Referring to step 3 of https://github.com/kubestellar/kubestellar/tree/main/docs/content/v0.20:

After the command: 

```shell
$ kflex create imbs1 --type vcluster -p ocm
✔ Checking for saved initial context...
✔ Switching to initial context...
✔ Creating new control plane imbs1 of type vcluster ...
✔ Waiting for API server to become ready...
```

The OCM pods do not seem to be working:

```shell
$ k --context kind-kubeflex get pods -A
NAMESPACE            NAME                                                READY   STATUS      RESTARTS   AGE
imbs1-system         coredns-68559449b6-swvrd-x-kube-system-x-vcluster   1/1     Running     0          46s
imbs1-system         ocm-cq5xm                                           0/1     Error       0          45s
imbs1-system         ocm-fbt5q                                           0/1     Error       0          27s
imbs1-system         update-cluster-info-5kqtf                           0/1     Completed   0          74s
imbs1-system         vcluster-0                                          2/2     Running     0          74s
```

The reported error is:

```shell
$ k --context kind-kubeflex logs ocm-cq5xm -n imbs1-system
exec /ko-app/clusteradm: exec format error
```

### Steps To Reproduce

See above

### Expected Behavior

Pods run

**Comment by pdettori** [comment] 2024-01-18 19:21
@francostellari what is your arch/os ? perhaps we do not have the build for that ?

**Comment by francostellari** [comment] 2024-01-18 20:01
Linux amd64

**Comment by francostellari** [comment] 2024-01-18 20:03
I could not figure out how to see the tags and arch of the ghrc.io registry. Pasting portions of the url does not work

**Comment by pdettori** [comment] 2024-01-18 23:21
The image is creating the issue is the job defined in https://github.com/kubestellar/kubestellar/blob/main/config/postcreate-hooks/ocm.yaml - the image is quay.io/kubestellar/clusteradm:0.7.1

**Comment by pdettori** [comment] 2024-01-18 23:25
Not sure I did the build for linux/amd64 - can you tell by looking at https://quay.io/repository/kubestellar/clusteradm?tab=tags ?

**Comment by francostellari** [comment] 2024-01-18 23:57
> Not sure I did the build for linux/amd64 - can you tell by looking at https://quay.io/repository/kubestellar/clusteradm?tab=tags ?

@pdettori It looks like that only linux/arm64 is available.
We need to build for other arches, at least linux/amd64

**Comment by pdettori** [comment] 2024-01-19 04:21
ok, will look into that

**Comment by pdettori** [comment] 2024-01-19 04:26
@francostellari  - actually I appreciate any help you could give here. There is no official OCI image for clusteradm, it's only a binary. The way I built it was to clone https://github.com/open-cluster-management-io/clusteradm, switch to latest tag - v0.7.2) and use ko to build the image above. It should use --platform linux/amd64,linux/arm64 .

**Comment by MikeSpreitzer** [comment] 2024-01-21 15:24
@pdettori , @francostellari : time to close this issue now?

**Comment by francostellari** [comment] 2024-01-21 15:59
I listed this issue in the pr. It should have closed automatically

**Closed** 2024-01-21 16:23 UTC
Labels: kind/bug
